# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HelloWorld.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10HelloWorld.proto\x12\nHelloWorld\"\x1a\n\nGetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x0bPostRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"(\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04json\x18\x02 \x01(\t2\x8d\x01\n\x14HelloWorldController\x12\x39\n\x06\x43reate\x12\x17.HelloWorld.PostRequest\x1a\x14.HelloWorld.Response\"\x00\x12:\n\x08Retrieve\x12\x16.HelloWorld.GetRequest\x1a\x14.HelloWorld.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HelloWorld_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETREQUEST._serialized_start=32
  _GETREQUEST._serialized_end=58
  _POSTREQUEST._serialized_start=60
  _POSTREQUEST._serialized_end=101
  _RESPONSE._serialized_start=103
  _RESPONSE._serialized_end=143
  _HELLOWORLDCONTROLLER._serialized_start=146
  _HELLOWORLDCONTROLLER._serialized_end=287
# @@protoc_insertion_point(module_scope)
